<Project>
  <PropertyGroup>
    <MBWGHLinguistWinX64AssetRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../nativeassets/win-x64'))</MBWGHLinguistWinX64AssetRoot>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64' and Exists('$(MBWGHLinguistWinX64AssetRoot)')">
    <Content Include="$(MBWGHLinguistWinX64AssetRoot)/**/*"
             Link="MBW.GHLinguist/%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest"
             Visible="false" />
  </ItemGroup>
</Project>
