<Project>
  <PropertyGroup>
    <MBWGHLinguistLinuxX64AssetRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../nativeassets/linux-x64'))</MBWGHLinguistLinuxX64AssetRoot>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64' and Exists('$(MBWGHLinguistLinuxX64AssetRoot)')">
    <Content Include="$(MBWGHLinguistLinuxX64AssetRoot)/**/*"
             Link="MBW.GHLinguist/%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest"
             CopyToPublishDirectory="PreserveNewest"
             Visible="false" />
  </ItemGroup>
</Project>
