<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <MinVerVersionOverride Condition="'$(CI_VERSION)' != ''">$(CI_VERSION)</MinVerVersionOverride>
  </PropertyGroup>
</Project>
