<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MBW.GHLinguist.PackageTopology.Library\MBW.GHLinguist.PackageTopology.Library.csproj" />
  </ItemGroup>
</Project>
