# frozen_string_literal: true

# Copies the DFA tables flex generated for Linguist's tokenizer into C#, so the managed tokenizer runs the exact
# same automaton as ext/linguist/linguist.so. Usage: ruby generate-tokenizer-tables.rb [lex.linguist_yy.c] [output.cs]

source_path = ARGV.fetch(0, File.expand_path("../../extern/linguist/ext/linguist/lex.linguist_yy.c", __dir__))
output_path = ARGV.fetch(1, File.expand_path("../../src/MBW.GHLinguist/Classification/LinguistTokenizerTables.g.cs", __dir__))
source = File.read(source_path)

def table(source, name)
  match = source.match(/static const \w+ #{name}\[(\d+)\] =\s*\{(.*?)\}\s*;/m) or abort("#{name} not found")
  values = match[2].scan(/-?\d+/).map(&:to_i)
  abort("#{name} has #{values.length} values, expected #{match[1]}") unless values.length == match[1].to_i
  values
end

def define(source, name)
  (source[/^#define #{name} (\d+)$/, 1] or abort("#{name} not found")).to_i
end

jam_state = source[/while \( yy_current_state != (\d+) \);/, 1] or abort("jam state not found")
meta_threshold = source[/if \( yy_current_state >= (\d+) \)/, 1] or abort("meta threshold not found")

tables = {
  "Accept" => ["short", table(source, "yy_accept")],
  "EquivalenceClasses" => ["byte", table(source, "yy_ec")],
  "Meta" => ["byte", table(source, "yy_meta")],
  "Base" => ["short", table(source, "yy_base")],
  "Default" => ["short", table(source, "yy_def")],
  "Next" => ["short", table(source, "yy_nxt")],
  "Check" => ["short", table(source, "yy_chk")]
}

File.open(output_path, "w", newline: :lf) do |output|
  output.puts "// <auto-generated>"
  output.puts "// Generated by eng/linguist/generate-tokenizer-tables.rb from Linguist's ext/linguist/lex.linguist_yy.c."
  output.puts "// Regenerate whenever extern/linguist changes; LinguistTokenizerTablesTests fails when this file is stale."
  output.puts "// </auto-generated>"
  output.puts
  output.puts "namespace MBW.GHLinguist.Classification;"
  output.puts
  output.puts "internal static class LinguistTokenizerTables"
  output.puts "{"
  output.puts "    internal const int EndOfBufferAction = #{define(source, 'YY_END_OF_BUFFER')};"
  output.puts "    internal const int JamState = #{jam_state};"
  output.puts "    internal const int MetaThreshold = #{meta_threshold};"
  tables.each do |name, (type, values)|
    output.puts
    output.puts "    internal static ReadOnlySpan<#{type}> #{name} =>"
    output.puts "    ["
    values.each_slice(16) { |slice| output.puts "        #{slice.join(', ')}," }
    output.puts "    ];"
  end
  output.puts "}"
end
