name: Build Linguist

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  linux-x64:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Linguist
        run: git submodule update --init extern/linguist
      - name: Build Linguist
        shell: pwsh
        run: ./eng/linguist/build-docker.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: linguist-linux-x64
          path: .tmp/artifacts/linguist/linux-x64
          if-no-files-found: error

  win-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Linguist
        shell: pwsh
        run: git submodule update --init extern/linguist
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0.1'
      - name: Build Linguist
        shell: pwsh
        run: ./eng/linguist/build-windows.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: linguist-win-x64
          path: .tmp/artifacts/linguist/win-x64
          if-no-files-found: error
