name: Build and Test

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  build-and-test:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            os: ubuntu-24.04
          - name: Windows
            os: windows-2022
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          global-json-file: global.json
      - name: Restore
        run: dotnet restore MBW.GHLinguist.slnx --nologo
      - name: Build
        run: dotnet build MBW.GHLinguist.slnx --configuration Release --no-restore --nologo
      - name: Test
        run: dotnet test --solution MBW.GHLinguist.slnx --configuration Release --no-build --minimum-expected-tests 1
